### ISSUE TITLE
Error at launch of Filter_mate 1.5

### ISSUE THREAD

**Issue by dd-a** [sducournau/filter_mate#1]
Hi, Filter_mate causes an error when launching QGIS.

`Impossible de charger l'extension 'filter_mate' provoque une erreur lors de l'appel à sa méthode classFactory() 

KeyError: 'APPDATA' 
Traceback (most recent call last):
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/didier/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/filter_mate/__init__.py", line 33, in classFactory
    from .filter_mate import FilterMate
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/didier/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/filter_mate/filter_mate.py", line 38, in 
    from .filter_mate_app import *
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/didier/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/filter_mate/filter_mate_app.py", line 16, in 
    from .config.config import *
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/didier/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/filter_mate/config/config.py", line 34, in 
    PLUGIN_CONFIG_DIRECTORY = os.path.normpath(os.environ['APPDATA'] + '\QGIS\QGIS3\profiles\default\FilterMate')
  File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'APPDATA'

Version de Python : 3.9.5 (default, Sep 10 2021, 16:18:19) [Clang 12.0.5 (clang-1205.0.22.11)] 
Version de QGIS : 3.28.13-Firenze Firenze, 3b4db4f5618 

Chemin Python :
/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python
/Users/didier/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/didier/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/plugins
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/scipy-1.5.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/geopandas-0.8.1-py3.9.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/pandas-1.3.3-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/opencv_contrib_python-4.3.0.36-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/Rtree-0.9.7-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/statsmodels-0.11.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/cftime-1.2.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/lib-dynload
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/rasterio-1.1.5-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python39.zip
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/netCDF4-1.5.4-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/patsy-0.5.1-py3.9.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/Pillow-7.2.0-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/matplotlib-3.3.0-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/pyproj-3.2.0-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/numpy-1.20.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/GDAL-3.3.2-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/Fiona-1.8.13.post1-py3.9-macosx-10.13.0-x86_64.egg
/Users/didier/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/didier/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/go2streetview
/Users/didier/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/go2streetview/res
/Users/didier/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/DataDrivenInputMask`

**Comment by sducournau** [comment]
Thanks for your feedback. This has been corrected and is part of the fixes for version 1.5.1 which will be validated soon.
https://github.com/sducournau/filter_mate/commit/10b4579117e2e4e7f840985f56fff3d1949e2b2f

**Comment by dd-a** [comment]
Cool !
